[package]
name = "actix-cache"
version = "0.1.0"
authors = ["Belousow Makc <lib.bmw@gmail.com>"]
edition = "2018"
description = "Actix cache actor."
license-file = "LICENSE"

[dependencies]
actix = "0.9"
log = "0.4"
actix-rt = "1"
actix-cache-redis = "0.1"

[workspace]
members = [
  ".",
  "actix-cache-redis"
]

[patch.crates-io]
actix-cache = { path = "." }
actix-cache-redis = { path = "actix-cache-redis" }
